Vagrant.configure("2") do |config|
    
    config.vm.define "webserver1" do |webserver1|
      webserver1.vm.box = "generic/centos9s"
      webserver1.vm.box_version = "4.3.12"
      config.vm.network "private_network", type: "dhcp"
      config.vm.provision "install openssh-server", type: "shell", inline:<<-SHELL
      sudo yum install -y openssh-server
      SHELL
      
    end
  
    config.vm.define "webserver2" do |webserver2|
      webserver2.vm.box = "ubuntu/trusty64"
      webserver2.vm.box_version = "20191107.0.0"
      config.vm.network "private_network", type: "dhcp"
    end
  end