Vagrant.configure("2") do |config|
  
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
  end

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "update-software", type: "shell", inline:<<-SHELL
  sudo apt update
  sudo add-apt-repository ppa:ansible/ansible
  sudo apt install -y software-properties-common
  sudo apt install -y ansible
  SHELL

end
